In [7]:
#Import Libraries
import numpy as np
import pandas as pd
import matplotlib.pylab as plt
import seaborn as sns#Understanding my variables

import project_functions as pf

In [16]:
df = pd.read_csv('housing.csv')
print("Rows vs Columns are "+ str(df.shape))

Rows vs Columns are (20640, 10)

In [17]:

print("Column titles are "+ str(df.columns))

Column titles are Index(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income',
       'median_house_value', 'ocean_proximity'],
      dtype='object')

In [14]:
df.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY

In [19]:
print ("The number of unique values for each variable are:")
df.nunique(axis=0)

The number of unique values for each variable are:

longitude               844
latitude                862
housing_median_age       52
total_rooms            5926
total_bedrooms         1923
population             3888
households             1815
median_income         12928
median_house_value     3842
ocean_proximity           5
dtype: int64

In [20]:
df.describe().apply(lambda s: s.apply(lambda x: format(x, 'f')))

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
count,20640.000000,20640.000000,20640.000000,20640.000000,20433.000000,20640.000000,20640.000000,20640.000000,20640.000000
mean,-119.569704,35.631861,28.639486,2635.763081,537.870553,1425.476744,499.539680,3.870671,206855.816909
std,2.003532,2.135952,12.585558,2181.615252,421.385070,1132.462122,382.329753,1.899822,115395.615874
min,-124.350000,32.540000,1.000000,2.000000,1.000000,3.000000,1.000000,0.499900,14999.000000
25%,-121.800000,33.930000,18.000000,1447.750000,296.000000,787.000000,280.000000,2.563400,119600.000000
50%,-118.490000,34.260000,29.000000,2127.000000,435.000000,1166.000000,409.000000,3.534800,179700.000000
75%,-118.010000,37.710000,37.000000,3148.000000,647.000000,1725.000000,605.000000,4.743250,264725.000000
max,-114.310000,41.950000,52.000000,39320.000000,6445.000000,35682.000000,6082.000000,15.000100,500001.000000

In [23]:
df.ocean_proximity.unique()

array(['NEAR BAY', '<1H OCEAN', 'INLAND', 'NEAR OCEAN', 'ISLAND'],
      dtype=object)

In [25]:
df.longitude.unique()

array([-122.23, -122.22, -122.24, -122.25, -122.26, -122.27, -122.28,
       -122.29, -122.3 , -122.21, -122.2 , -122.19, -122.18, -122.13,
       -122.16, -122.17, -122.15, -122.14, -122.12, -122.33, -122.34,
       -122.06, -122.07, -122.08, -122.09, -122.1 , -122.11, -122.03,
       -121.97, -122.02, -122.04, -122.05, -121.99, -122.01, -121.96,
       -121.98, -122.  , -121.93, -121.94, -121.95, -121.92, -121.89,
       -121.91, -121.9 , -121.88, -121.87, -121.85, -121.86, -121.84,
       -121.82, -121.77, -121.62, -121.61, -121.72, -121.73, -121.75,
       -121.8 , -121.76, -121.78, -121.79, -119.78, -119.93, -120.  ,
       -120.56, -120.59, -120.55, -120.25, -120.79, -120.8 , -120.65,
       -120.76, -120.88, -120.69, -120.93, -120.97, -120.87, -120.98,
       -120.72, -120.77, -120.66, -120.62, -120.71, -121.83, -121.81,
       -121.74, -121.68, -121.54, -121.51, -121.59, -121.58, -121.6 ,
       -121.63, -121.57, -121.65, -121.64, -121.71, -121.66, -121.56,
       -121.5 , -121.41, -121.39, -121.24, -121.19, -121.36, -121.46,
       -121.49, -121.44, -121.47, -121.53, -121.52, -121.55, -121.67,
       -121.69, -121.7 , -120.46, -120.54, -120.67, -120.9 , -120.91,
       -120.57, -120.43, -120.42, -120.41, -120.36, -120.34, -120.33,
       -120.37, -120.27, -120.19, -122.51, -122.32, -122.36, -122.31,
       -122.39, -122.37, -122.41, -122.35, -122.38, -122.42, -124.17,
       -124.3 , -124.23, -124.21, -124.19, -124.22, -124.16, -124.14,
       -124.15, -123.91, -123.83, -123.92, -119.94, -119.95, -119.97,
       -119.98, -119.96, -119.99, -120.01, -120.02, -119.92, -120.04,
       -120.03, -120.13, -120.16, -120.06, -120.1 , -121.04, -120.92,
       -120.84, -120.81, -120.5 , -120.3 , -121.09, -121.08, -121.07,
       -121.06, -121.  , -121.01, -120.99, -121.02, -120.95, -120.96,
       -120.86, -120.83, -120.78, -120.7 , -120.58, -120.6 , -120.63,
       -120.44, -120.32, -120.08, -120.85, -119.81, -119.79, -119.8 ,
       -119.77, -119.82, -119.83, -119.74, -119.76, -119.75, -119.69,
       -119.67, -119.73, -119.72, -119.71, -119.63, -119.65, -119.68,
       -119.89, -119.87, -119.85, -119.84, -119.7 , -119.86, -119.9 ,
       -120.21, -120.05, -120.07, -119.91, -119.88, -119.64, -119.53,
       -119.58, -119.59, -119.5 , -119.57, -119.56, -119.55, -119.54,
       -119.52, -119.47, -119.41, -119.43, -119.39, -119.4 , -119.49,
       -119.61, -119.48, -119.46, -119.33, -119.21, -118.94, -119.34,
       -119.28, -119.32, -118.91, -119.24, -119.25, -119.12, -119.31,
       -119.44, -119.45, -119.6 , -119.62, -120.09, -120.38, -120.35,
       -120.31, -120.18, -120.22, -120.51, -120.39, -120.45, -122.74,
       -122.53, -124.18, -124.11, -124.13, -124.06, -124.05, -124.02,
       -124.08, -124.09, -124.07, -124.1 , -123.74, -123.76, -123.85,
       -123.72, -123.63, -123.66, -123.52, -124.01, -124.  , -123.98,
       -123.88, -124.27, -123.96, -123.73, -124.03, -124.26, -124.35,
       -124.25, -123.84, -123.68, -123.82, -123.75, -123.78, -115.52,
       -115.51, -115.46, -115.6 , -115.73, -115.62, -115.41, -115.59,
       -115.53, -115.54, -115.55, -115.56, -115.32, -115.39, -115.4 ,
       -115.37, -115.38, -115.57, -115.49, -115.64, -115.69, -115.72,
       -115.58, -115.48, -115.5 , -116.05, -116.  , -115.88, -115.9 ,
       -116.01, -115.99, -115.94, -115.98, -115.91, -115.96, -115.95,
       -115.8 , -114.73, -114.98, -114.65, -114.55, -114.63, -114.66,
       -118.18, -118.43, -118.6 , -118.45, -118.42, -118.4 , -118.39,
       -118.3 , -117.9 , -118.31, -118.05, -117.69, -117.02, -116.22,
       -119.02, -119.03, -119.05, -119.04, -119.08, -119.07, -119.09,
       -119.11, -119.01, -118.99, -119.  , -118.97, -118.98, -118.96,
       -118.95, -118.92, -118.9 , -118.87, -118.88, -118.93, -119.06,
       -119.1 , -119.13, -119.15, -119.16, -119.42, -119.19, -119.2 ,
       -119.18, -119.27, -119.26, -119.38, -119.36, -119.35, -119.14,
       -119.29, -119.22, -119.23, -118.06, -118.44, -118.47, -118.5 ,
       -118.59, -118.23, -118.33, -118.41, -118.48, -118.61, -117.73,
       -117.66, -117.67, -117.68, -117.7 , -117.64, -117.76, -117.81,
       -117.87, -117.84, -117.74, -118.  , -117.82, -117.79, -118.01,
       -117.98, -117.95, -117.99, -118.27, -118.34, -117.65, -118.15,
       -118.17, -118.19, -118.16, -118.51, -118.66, -118.46, -118.83,
       -118.85, -118.82, -119.66, -120.14, -120.12, -122.89, -122.9 ,
       -122.91, -122.88, -123.07, -122.95, -122.92, -122.94, -122.99,
       -122.7 , -122.87, -122.86, -122.83, -122.79, -122.8 , -122.78,
       -122.69, -122.73, -122.66, -122.65, -122.52, -122.68, -122.63,
       -122.62, -122.61, -122.6 , -122.64, -122.75, -122.71, -122.85,
       -122.84, -122.77, -122.72, -122.48, -122.59, -122.5 , -122.55,
       -121.11, -121.03, -120.64, -120.49, -120.2 , -118.28, -118.29,
       -118.35, -118.32, -118.36, -118.38, -118.49, -118.52, -118.54,
       -118.55, -118.57, -118.53, -118.63, -118.62, -118.64, -118.56,
       -118.58, -118.37, -118.65, -118.22, -118.2 , -118.21, -118.24,
       -118.25, -118.26, -117.71, -117.78, -117.8 , -117.83, -117.93,
       -117.91, -117.89, -117.88, -117.85, -117.86, -117.77, -117.75,
       -117.72, -117.92, -117.94, -117.97, -117.96, -118.02, -118.03,
       -118.04, -118.07, -118.08, -118.09, -118.1 , -118.11, -118.12,
       -118.13, -118.14, -118.69, -118.67, -118.68, -118.76, -118.75,
       -118.72, -118.78, -118.8 , -118.84, -118.79, -118.74, -118.86,
       -118.7 , -119.51, -120.26, -120.29, -120.11, -122.49, -122.54,
       -122.58, -122.57, -122.56, -122.44, -122.45, -122.47, -122.46,
       -122.93, -122.96, -122.81, -120.15, -123.15, -123.24, -123.23,
       -123.47, -123.71, -123.58, -123.5 , -123.64, -123.79, -123.8 ,
       -123.34, -123.4 , -123.32, -123.38, -123.35, -123.37, -123.36,
       -123.1 , -123.11, -123.18, -123.22, -123.21, -123.19, -123.2 ,
       -123.81, -123.7 , -123.53, -123.69, -123.59, -123.54, -123.39,
       -123.17, -123.16, -120.68, -120.75, -120.74, -120.73, -120.94,
       -120.89, -120.61, -120.48, -120.47, -120.4 , -120.24, -120.82,
       -121.16, -121.18, -119.3 , -121.43, -121.45, -121.42, -121.48,
       -121.31, -121.32, -121.33, -121.4 , -121.23, -121.25, -121.26,
       -121.12, -121.13, -121.2 , -122.4 , -121.1 , -121.05, -121.22,
       -121.14, -121.21, -121.15, -120.17, -120.23, -117.62, -117.6 ,
       -117.63, -117.55, -117.59, -117.58, -117.49, -117.53, -117.61,
       -121.17, -121.27, -121.28, -121.3 , -121.29, -120.53, -117.35,
       -117.36, -117.37, -117.38, -117.39, -117.41, -117.4 , -117.44,
       -117.43, -117.42, -117.45, -117.5 , -117.48, -117.47, -117.51,
       -117.52, -117.56, -117.57, -117.46, -117.54, -117.33, -117.34,
       -117.26, -117.3 , -117.28, -117.32, -117.31, -117.29, -117.24,
       -117.23, -117.25, -117.21, -117.14, -117.27, -117.22, -117.16,
       -117.13, -117.19, -117.17, -117.2 , -117.07, -117.11, -117.08,
       -117.18, -117.06, -117.09, -117.15, -117.12, -117.05, -116.96,
       -117.1 , -116.99, -116.91, -116.89, -116.95, -116.9 , -116.92,
       -116.93, -116.94, -116.97, -116.98, -117.01, -117.  , -116.87,
       -116.88, -116.86, -117.04, -117.03, -116.79, -116.77, -116.81,
       -116.75, -116.8 , -116.71, -116.68, -116.74, -116.72, -116.48,
       -116.57, -116.76, -116.42, -116.6 , -116.69, -116.39, -116.51,
       -116.61, -116.44, -116.36, -116.52, -116.53, -116.5 , -116.47,
       -116.63, -116.54, -116.55, -116.49, -116.56, -116.46, -116.43,
       -116.45, -116.4 , -116.38, -116.33, -116.31, -116.37, -116.41,
       -116.29, -116.3 , -116.26, -116.25, -116.24, -116.21, -116.23,
       -116.2 , -116.15, -116.11, -116.17, -116.12, -115.84, -116.16,
       -116.19, -116.18, -116.08, -115.22, -114.67, -114.49, -114.68,
       -114.56, -114.57, -114.59, -114.61, -114.6 , -114.58, -114.62,
       -121.38, -121.37, -121.35, -121.34, -115.93, -115.75, -116.14,
       -116.32, -116.27, -116.35, -116.62, -116.73, -116.06, -116.09,
       -116.02, -115.85, -114.94, -114.47, -114.31, -114.64, -116.85,
       -116.83, -116.82, -116.84, -116.78, -116.58, -116.66, -116.67,
       -116.34, -116.28, -122.43, -120.52, -122.76, -123.26, -123.41,
       -123.08, -122.67, -122.82, -123.04, -123.02, -122.98, -123.01,
       -123.  , -122.97, -123.03, -123.49, -123.25, -123.48, -123.28,
       -123.13, -123.12, -123.43, -119.37, -118.73, -120.28, -119.17,
       -118.89, -118.81, -118.77, -118.71])

In [27]:
# plot pop vs location in a heatmap
locations_pop = df_cleaned
locations_pop = locations_pop.pivot( 'latitude',"longitude", 'population' )
ax = sns.heatmap(locations_pop)

ValueError: Index contains duplicate entries, cannot reshape